snapcap_responses = [
    "Snap upni biwi ko divorce mat de",
    "Papa came back with the milk",
    "Papa mene blackie se shadi kar li",
    "Snap did you adopt again?",
    "Snap Manno ka pankha wapas karde",
    "I love you too",
    "We should sleep together",
    "I can heal you",
    "Me looking for a fuck I'm supposed to give",
    "snapbot better",
    "talk to me babygurl"
]

greeting_responses = [
    "Hey there!",
    "Hi!",
    "Hello!",
    "Hey!",
    "Hi, how are you?",
    "Hello, good to see you!",
    "Hey, what's up?",
    "Hi, nice to meet you!",
    "Hello, how have you been?",
    "Hey, how's it going?",
    "Hi, how's your day?",
    "Hello, how are things?",
    "Hey, long time no see!",
    "Hi there, how can I help you?",
    "Hello, what's new?",
    "Hey, howdy!",
    "Hi, good to hear from you!",
    "Hello, nice weather today, isn't it?",
    "Hey, how's everything going?",
    "Hi, what's going on?"
]

interesting_questions = [
    "What's the most interesting thing you've learned recently?",
    "If you could travel anywhere in the world right now, where would you go and why?",
    "What's a book, movie, or TV show you've recently enjoyed and would recommend?",
    "If you could have any superpower, what would it be and how would you use it?",
    "What's your favorite hobby or pastime?",
    "If you could meet any historical figure, who would it be and what would you ask them?",
    "What's the best piece of advice you've ever received?",
    "If you could only eat one food for the rest of your life, what would it be?",
    "What's something on your bucket list that you hope to accomplish someday?",
    "If you could switch lives with any fictional character for a day, who would it be and why?",
    "What's a skill or talent you wish you had?",
    "What's the most memorable dream you've ever had?",
    "If you could go back in time and change one event in history, what would it be?",
    "What's a song that always puts you in a good mood?",
    "If you could have dinner with any three people, living or dead, who would you choose and why?",
    "What's the most adventurous thing you've ever done?",
    "If you could have any animal as a pet, what would it be?",
    "What's a skill you've always wanted to learn but haven't had the chance to yet?",
    "If you could live in any fictional universe, which one would you choose?",
    "What's a piece of technology you can't live without?",
    "If you could witness any event in history, what would it be?",
    "What's your favorite thing about yourself?",
    "If you could go on a road trip with any three people, who would you choose?",
    "What's the most spontaneous thing you've ever done?",
    "What's the most interesting place you've ever visited?",
    "If you could only watch one genre of movies for the rest of your life, what would it be?",
    "What's something you're passionate about?",
    "If you could have any job in the world, what would it be?",
    "What's a talent you have that most people don't know about?",
    "If you could time travel to any period in your own life, when would you go and why?",
    "What's your favorite season and why?",
    "If you could have any fictional character as a best friend, who would it be?",
    "What's the most delicious food you've ever tasted?",
    "If you could live in any time period, past or future, when would it be?",
    "What's a goal you're currently working towards?",
    "If you could have any famous person narrate your life, who would it be?",
    "What's the most adventurous thing you've ever done?",
    "If you could have any animal as a pet, what would it be?",
    "What's a skill you've always wanted to learn but haven't had the chance to yet?",
    "If you could live in any fictional universe, which one would you choose?",
    "What's a piece of technology you can't live without?",
    "If you could witness any event in history, what would it be?",
    "What's your favorite thing about yourself?",
    "If you could go on a road trip with any three people, who would you choose?",
    "What's the most spontaneous thing you've ever done?",
    "What's the most interesting place you've ever visited?",
    "If you could only watch one genre of movies for the rest of your life, what would it be?",
    "What's something you're passionate about?",
    "If you could have any job in the world, what would it be?",
    "What's a talent you have that most people don't know about?",
    "If you could time travel to any period in your own life, when would you go and why?",
    "What's your favorite season and why?",
    "If you could have any fictional character as a best friend, who would it be?",
    "What's the most delicious food you've ever tasted?",
    "If you could live in any time period, past or future, when would it be?",
    "What's a goal you're currently working towards?",
    "If you could have any famous person narrate your life, who would it be?",
    "What's a skill you admire in others and wish you had?",
    "If you could have any fictional character as a roommate, who would it be?",
    "What's the best piece of advice you've ever received from a family member?",
    "If you could have any job in the world for one day, what would it be?",
    "What's a food you disliked as a child but love now?",
    "If you could eliminate one thing from your daily routine, what would it be?",
    "What's a movie or book that significantly impacted your life?",
    "If you could bring back any fashion trend, what would it be?",
    "What's a talent you have that surprises people?",
    "If you could only listen to one genre of music for the rest of your life, what would it be?",
    "What's the most underrated TV show or movie you've seen?",
    "If you could have any fictional character's wardrobe, whose would it be?",
    "What's a skill you've developed during the pandemic?",
    "If you could have any animal's abilities for a day, which animal would you choose?",
    "What's a goal you've achieved that you're most proud of?",
    "If you could teleport anywhere in the world right now, where would you go?",
    "What's a topic you're passionate about but don't often get to discuss?",
    "If you could have dinner with any celebrity, who would it be?",
    "What's the most interesting job you've ever had?",
    "If you could have any movie character's life, whose would you choose?",
    "What's a habit you've been trying to break?",
    "If you could spend a day with any fictional character, who would it be and what would you do?",
    "What's a place you've always wanted to live but haven't had the chance to?",
    "If you could have any historical artifact, what would it be?"
]
